// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvjcugjxrtnvjfjjgpfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12amN1Z2p4cnRudmpmampncGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDMwMDQsImV4cCI6MjA2NzA3OTAwNH0.eP-lH3CtnrVC6ukbZypmizq3jnSqLdUnZ1zfIYGXDqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});